export const privacyPolicyContent = [
  {
    id: 'p1',
    heading: 'General Statistics & Web Site Measurments',
    text: `We collect aggregate information site-wide, including anonymous site statistics. We also log domain names and/or IP addresses. We use your IP address to help diagnose problems with our server, and to administer our web site as well as improve the site-wide experience for you and other users. We also link IP addresses to personally identifiable information within our eCommerce site in order to ensure the security of our service for all users. In these cases, the IP address and personally identifiable information becomes part of an audit trail that we may use to identify the source of a specific transaction.We identify and track the single, previous Web site address that visitors come from when accessing our site. This is standard practice throughout the Internet, and it is used to determine how visitors navigate to our sites. We do not, however, attach this information to anything that is personally identifiable. In other words, while we may track what site you came from, we do not directly connect that information with anything that identifies you.When a visitor registers, "logs in," or accesses parts of our site that require the use of data like usernames and passwords, we may store a cookie, a small piece of information, on that visitor's computer.If used, this small file helps to improve the user's experience by allowing us to customize or tailor the web pages that the visitor sees and uses for their specific needs. For example, we may use a cookie to allow a user to by-pass having to enter their username every time they login. For frequent visitors, this type of functionality and personalization can greatly improve their experience. These cookies DO NOT contain confidential or personal information. While we may use cookies to help us understand and improve the navigation of our site, we DO NOT use cookies to personally identify and track the navigation of any specific visitor.We do not resell, distribute, or disclose any of the above information to third parties.`,
  },
  {
    id: 'p2',
    heading: 'Registration & Personally Identifiable Information',
    text: `On certain pages, we may give users the option of providing us with names, addresses, phone numbers, fax numbers, e-mail addresses, demographic data, preference information, and various other kinds of details. This more personal information is not gathered by us without the users' knowledge, active permission, and participation. In other words, you must voluntarily supply this information. On the Internet, this voluntary submission of personally identifiable information is commonly referred to as "Opting In." In some cases we may use the information to tailor our users' web experience, generate anonymous statistics, or to contact users via e-mail, postal mail, telephone, or fax (e.g. to send newsletters, action alerts, product updates, etc.) Users may choose opt out at any time; see the cancel subscription section below. For security purposes, the e-commerce capability of our site requires users to give us unique identifiers (like social security number and other password-type data). Unique identifiers are collected to verify the user's identity and ensure security for all users of the site. WE DO NOT RESELL, DISTRIBUTE, OR DISCLOSE ANY OF THE DATA THAT HAS BEEN DISCUSSED IN THE PRECEDING SECTION (REGISTRATION & PERSONALLY IDENTIFIABLE INFORMATION) TO THIRD PARTIES.`,
  },
  {
    id: 'p3',
    heading: 'Security & Protection of Your Data',
    text: `This site has security measures in place to protect the loss, misuse and alteration of the information under our control. Portions of our site make extensive use of Secure Sockets Layer (SSL) encryption, the Internet's leading encryption standard, as well as password-like identifying information. SSL is used to encrypt the information being sent between a visitor’s computer and our web site. Encryption is a process in which the information being transmitted between two parties is "scrambled" in transit. SSL encryption creates a secure link between two computers by establishing a process in which each computer can unscramble (unencrypt) the other's information. Because we take the protection of your data very seriously, you may be asked to "upgrade" your Internet browser to a more recent version if it does not currently support the high levels of SSL encryption that portions of our web site require. Your browser should indicate whether or not it is operating in a secure site. Most browsers will display an alert box advising you that you are requesting pages from a secure site, and they will ask your permission to continue. Most browsers will also alert you when you are leaving a secure site, and again, ask you permission to continue. However, this alert feature can be turned off within the browser's preferences. If you have doubts about whether or not you are on a secured web page, contact the web site's operator to clarify your questions, and DO NOT transmit sensitive information like credit card numbers until you are confident of the page's security. In addition, we take great care to safeguard all information that is transmitted to us and stored by us on our computers, servers, and databases. This protection includes the use of network intrusion prevention and detection technology as well as other industry accepted security practices. We protect the physical location of our systems through the use of access control and monitoring technologies. We take extensive measures to limit the risk of damage or loss of any data due to hazards like fire, water damage, power loss, etc.`,
  },
]

export const termsContent = [
  {
    id: 'p1',
    heading: 'Registration, Accounts & Passwords',
    text: `Certain of the Services and related features made available on a HR Work Cycles Site may require registration or subscription. Should you choose to register or subscribe for any such Services or related features, you agree to provide accurate and current information about yourself as required by the relevant registration or subscription process, and to promptly update such information as necessary to ensure that it is kept accurate and complete. You agree to be responsible for: (a) maintaining the confidentiality of any passwords or other account identifiers which you choose or are assigned as a result of any registration or subscription on a HR Work Cycles Site, and (b) all activities that occur under such password or account. Further, you agree to notify HR Work Cycles of any unauthorized use of your password or account. HR Work Cycles shall not be responsible or liable, directly or indirectly, in any way for any loss or damage of any kind incurred as a result of, or in connection with, your failure to comply with this Section.`,
  },
  {
    id: 'p2',
    heading: 'Restrictions on Use of Materials',
    text: `All material, information and content (collectively "Content") available on a HR Work Cycles Site, including the manner in which such Content is presented, and the Services are: Copyright © HR Work Cycles, its affiliates and/or licensors. All rights reserved. Such Content is protected by US and worldwide copyright laws and treaty provisions. HR Work Cycles grants you a limited non-exclusive, non-transferable license to use and display on your computer or other electronic access device, the Content and Services for your own personal and non-commercial use only, provided that you do not modify the Content and that you maintain all copyright and other proprietary notices. Except as provided herein, you agree not to reproduce, make derivative works of, retransmit, distribute, sell, publish, communicate, broadcast or otherwise make available any of the Content obtained through a HR Work Cycles Site or any of the Services, including without limitation, by caching, framing or similar means, without the prior written consent of the respective copyright owner of such Content.`,
  },
  {
    id: 'p3',
    heading: 'Registration, Accounts & Passwords',
    text: `Certain of the Services and related features made available on a HR Work Cycles Site may require registration or subscription. Should you choose to register or subscribe for any such Services or related features, you agree to provide accurate and current information about yourself as required by the relevant registration or subscription process, and to promptly update such information as necessary to ensure that it is kept accurate and complete. You agree to be responsible for: (a) maintaining the confidentiality of any passwords or other account identifiers which you choose or are assigned as a result of any registration or subscription on a HR Work Cycles Site, and (b) all activities that occur under such password or account. Further, you agree to notify HR Work Cycles of any unauthorized use of your password or account. HR Work Cycles shall not be responsible or liable, directly or indirectly, in any way for any loss or damage of any kind incurred as a result of, or in connection with, your failure to comply with this Section.`,
  },
  {
    id: 'p4',
    heading: 'Restrictions on Use of Materials',
    text: `All material, information and content (collectively "Content") available on a HR Work Cycles Site, including the manner in which such Content is presented, and the Services are: Copyright © HR Work Cycles, its affiliates and/or licensors. All rights reserved. Such Content is protected by US and worldwide copyright laws and treaty provisions. HR Work Cycles grants you a limited non-exclusive, non-transferable license to use and display on your computer or other electronic access device, the Content and Services for your own personal and non-commercial use only, provided that you do not modify the Content and that you maintain all copyright and other proprietary notices. Except as provided herein, you agree not to reproduce, make derivative works of, retransmit, distribute, sell, publish, communicate, broadcast or otherwise make available any of the Content obtained through a HR Work Cycles Site or any of the Services, including without limitation, by caching, framing or similar means, without the prior written consent of the respective copyright owner of such Content.`,
  },
]
